name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-waka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update WakaTime section
        uses: athul/waka-readme@v3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

